[package]
name = "gui_timer"
version = "0.1.0"
edition = "2024"

[dependencies]
comms = { version = "0.1.0", path = "../comms" }
eframe = { version = "0.31.1", features = ["persistence"] }
egui = "0.31.1"
interprocess = "2.2.3"
serde = "1.0.219"
